### ISSUE TITLE
Consider returning validation errors instead of throwing an exception

### ISSUE THREAD

**Issue by hawkaa** [tskj/typescript-json-decoder#2] opened 2021-05-20 22:16 UTC
Hi!

I just started using your library and I am really impressed. I've been looking for `pydantic` equivalents in the TypeScript world and this fits the bill.

I just wonder if you have considered making the validation exceptions an actual return type instead of throwing an exception?

Right now, my handler looks like this, with an odd looking `let` statement:

```typescript
  let input
  try {
    input = inputDecoder(JSON.parse(body))
  } catch (e) {
    return {
      statusCode: 400,
      body: e.message,
    }
  }
```

While there are tons of ways around this, have you ever considered an interface that looks something like this?

```typescript
const input = inputDecoder(JSON.parse(body))
if (typeof input === string) {
    return {
      statusCode: 400,
      body: e.message,
    }
}
```

Either works, and it is easy to get around and/or make abstractions on top of the input decoder. I just wanted to ask whether this is something you've considered.

Håkon

**Comment by tskj** [comment] 2021-05-21 07:51
Hi! Thanks for giving my library a try!

I've definitely considered it, the problem is that decoders would not compose if the return value is potentially an error. Consider the case where you build up a record:

```typescript
const dec = record({
  x: inputDecoder(JSON.parse(body)),
  ...
});
```

You definitely don't want `x` to be an error type here.

I've been thinking about adding a default decoder which let's you specify default values in a slick way. This could definitely be used to replace the actual value with an error value on failure.

**Comment by hawkaa** [comment] 2021-05-21 09:47
> You definitely don't want x to be an error type here.
You definitely not. But I guess there are ways to deal with that as well, but probably not as straight forward.

That said, I am happy with the way it works! We might make some abstractions over your library to make it align slightly more with our programming style. :)

**Comment by tskj** [comment] 2021-05-25 09:17
Well it's definitely possible, but I think you would be forced to have a _discriminated_ union, to be absolutely sure that you can differentiate the error condition from the ok case, which necessarily would result in the return value from the decoder being wrapped up in some kind of `{ ok: true, data: ... }` structure. I'm definitely a fan of these kinds of patterns in functional languages that have the necessary infrastructure to make it easy to deal with, but it seemed more idiomatic to throw an exception in TypeScript - especially considering how well that plays with Promises! The alternative of `Promise<Result<MyDecodedType>>` instead of just `Promise<MyDecodedType>` seems like a worse default, but I definitely see why you could want to opt in to something like that.

I would encourage you to share the abstraction you come up with on this issue or a new one, I'm super curious what you come up with!

**Comment by hawkaa** [comment] 2021-05-27 19:04
> I'm definitely a fan of these kinds of patterns in functional languages that have the necessary infrastructure to make it easy to deal with, but it seemed more idiomatic to throw an exception in TypeScript

I think you're spot on here! Agree 100%

> especially considering how well that plays with Promises! 

You mean that exceptions actually work with promises and await/async?

I hope I am not wasting your time. I just like the occasional discussion about this 👍🏻  Thank you for taking the time! :D 

> I would encourage you to share the abstraction you come up with on this issue or a new one, I'm super curious what you come up with!

You're going to be dissapointed. It's not an abstraction specific to this library. We've just created a middleware in our serverless framework lambdas that looks like this: 

```typescript

type HandlerParameters = {
  queryStringParameters: { [key: string]: string | undefined }
  pathParameters: { [key: string]: string | undefined }
}
type Handler = (parameters: HandlerParameters) => Promise<APIGatewayProxyResult>
type HandlerWithDecoder<T> = (parameters: HandlerParameters & { body: T }) => Promise<APIGatewayProxyResult>
/**
 * This middleware can be used for our POST handlers to make parsing of the input data easier. It
 * accepts a decoderFunction from "typescript-json-decoder" and handles that parsing before invoking
 * the actual implementation
 */
export function createHandlerWithDecoder<T>(
  decoderFunction: DecoderFunction<T>,
  handler: HandlerWithDecoder<T>,
): (e: APIGatewayProxyEvent) => Promise<APIGatewayProxyResult> {
  return async (event: APIGatewayProxyEvent) => {
    console.info("Received event", event)

    const body: unknown = event.body
    if (typeof body !== "string") {
      return {
        statusCode: 400,
        body: "Missing body",
      }
    }
    let input: T
    try {
      input = decoderFunction(event.isBase64Encoded ? JSON.parse(base64Decode(body)) : JSON.parse(body))
    } catch (e) {
      return {
        statusCode: 400,
        body: e.message,
      }
    }
    return handler({
      // Normalize such that an undefined queryStringParametersObject is turned into an empty object
      queryStringParameters: event.queryStringParameters || {},
      pathParameters: event.pathParameters || {},
      body: input,
    })
  }
}
```

**Comment by tskj** [comment] 2021-05-28 08:32
Yes! Exceptions work very well with promises! You can throw anywhere inside an `async` function or within the `.then(..)` handler of a promise, and that will result in the promise being rejected with the exception you throw.

In the code you've shown here, it seems you are returning a valid value (that is, resolving the promise) in all code paths, so this might be different than what you want. But for most usecases I have seen, having the decoder automatically reject the promise is super nice. In that case it also typically makes sense to reject the promise when you detect a bad status code, such as 400.

**Closed as completed** 2021-06-01 17:50 UTC
